const schools = [
		{value: 'Georgia Tech'},
		{value: 'Emory'},
		{value: 'University of Georgia'},
];

const locations = [
		{value: 'Atlanta, GA'},
];

const majors = [
	{value: 'Mechanical Engineering'},
	{value: 'Computer Science'},
	{value: 'Electrical Engineering'},
	{value: 'Industrial Engineering'},
  {value: 'Accounting'},
  {value: 'Actuarial Science'},
  {value: 'Advertising And Public Relations'},
  {value: 'Aerospace Engineering'},
  {value: 'Agricultural Economics'},
  {value: 'Agriculture Production And Management'},
  {value: 'Animal Sciences'},
  {value: 'Anthropology And Archeology'},
  {value: 'Applied Language and Intercultural Studies'},
  {value: 'Applied Mathematics'},
  {value: 'Applied Physics'},
  {value: 'Architectural Engineering'},
  {value: 'Architecture'},
  {value: 'Area Ethnic And Civilization Studies'},
  {value: 'Art And Music Education'},
  {value: 'Art History And Criticism'},
  {value: 'Astronomy And Astrophysics'},
  {value: 'Atmospheric Sciences And Meteorology'},
  {value: 'Biochemical Sciences'},
  {value: 'Biochemistry'},
  {value: 'Biological Engineering'},
  {value: 'Biology'},
  {value: 'Biomedical Engineering'},
  {value: 'Botany'},
  {value: 'Business Administration'},
  {value: 'Business Economics'},
  {value: 'Business Management And Administration'},
  {value: 'Chemical and Biomolecular Engineering'},
  {value: 'Chemical Engineering'},
  {value: 'Chemistry'},
  {value: 'Civil Engineering'},
  {value: 'Clinical Psychology'},
  {value: 'Cognitive Science And Biopsychology'},
  {value: 'Commercial Art And Graphic Design'},
  {value: 'Communication Disorders Sciences And Services'},
  {value: 'Communication Technologies'},
  {value: 'Communications'},
  {value: 'Community And Public Health'},
  {value: 'Composition And Rhetoric'},
  {value: 'Computational Media'},
  {value: 'Computer Administration Management And Security'},
  {value: 'Computer And Information Systems'},
  {value: 'Computer Engineering'},
  {value: 'Computer Networking And Telecommunications'},
  {value: 'Computer Programming And Data Processing'},
  {value: 'Computer Science'},
  {value: 'Construction Services'},
  {value: 'Cosmetology Services And Culinary Arts'},
  {value: 'Counseling Psychology'},
  {value: 'Court Reporting'},
  {value: 'Criminal Justice And Fire Protection'},
  {value: 'Criminology'},
  {value: 'Drama And Theater Arts'},
  {value: 'Early Childhood Education'},
  {value: 'Earth and Atmospheric Sciences'},
  {value: 'Ecology'},
  {value: 'Economics'},
  {value: 'Economics and International Affairs'},
  {value: 'Educational Administration And Supervision'},
  {value: 'Educational Psychology'},
  {value: 'Electrical Engineering'},
  {value: 'Electrical Engineering Technology'},
  {value: 'Electrical, Mechanical, And Precision Technologies And Production'},
  {value: 'Elementary Education'},
  {value: 'Engineering And Industrial Management'},
  {value: 'Engineering Mechanics Physics And Science'},
  {value: 'Engineering Technologies'},
  {value: 'English Language And Literature'},
  {value: 'Environmental Engineering'},
  {value: 'Environmental Science'},
  {value: 'Family And Consumer Sciences'},
  {value: 'Film Video And Photographic Arts'},
  {value: 'Finance'},
  {value: 'Fine Arts'},
  {value: 'Food Science'},
  {value: 'Forestry'},
  {value: 'French German Latin And Other Common Foreign Language Studies'},
  {value: 'General Agriculture'},
  {value: 'General Business'},
  {value: 'General Education'},
  {value: 'General Engineering'},
  {value: 'General Medical And Health Services'},
  {value: 'General Social Sciences'},
  {value: 'Genetics'},
  {value: 'Geography'},
  {value: 'Geological And Geophysical Engineering'},
  {value: 'Geology And Earth Science'},
  {value: 'Geosciences'},
  {value: 'Global Economics and Modern Languages'},
  {value: 'Health And Medical Administrative Services'},
  {value: 'Health And Medical Preparatory Programs'},
  {value: 'History'},
  {value: 'History, Technology, and Society'},
  {value: 'Hospitality Management'},
  {value: 'Human Resources And Personnel Management'},
  {value: 'Human Services And Community Organization'},
  {value: 'Humanities'},
  {value: 'Industrial And Manufacturing Engineering'},
  {value: 'Industrial And Organizational Psychology'},
  {value: 'Industrial Design'},
  {value: 'Industrial Engineering'},
  {value: 'Industrial Production Technologies'},
  {value: 'Information Sciences'},
  {value: 'Intercultural And International Studies'},
  {value: 'Interdisciplinary Social Sciences'},
  {value: 'International Affairs'},
  {value: 'International Affairs and Modern Languages'},
  {value: 'International Business'},
  {value: 'International Relations'},
  {value: 'Journalism'},
  {value: 'Language And Drama Education'},
  {value: 'Liberal Arts'},
  {value: 'Library Science'},
  {value: 'Linguistics And Comparative Language And Literature'},
  {value: 'Literature, Media, and Communication'},
  {value: 'Management Information Systems And Statistics'},
  {value: 'Marketing And Marketing Research'},
  {value: 'Mass Media'},
  {value: 'Materials Engineering And Materials Science'},
  {value: 'Materials Science'},
  {value: 'Materials Science and Engineering'},
  {value: 'Mathematics'},
  {value: 'Mathematics And Computer Science'},
  {value: 'Mathematics Teacher Education'},
  {value: 'Mechanical Engineering'},
  {value: 'Mechanical Engineering Related Technologies'},
  {value: 'Medical Assisting Services'},
  {value: 'Medical Technologies Technicians'},
  {value: 'Metallurgical Engineering'},
  {value: 'Microbiology'},
  {value: 'Military Technologies'},
  {value: 'Mining And Mineral Engineering'},
  {value: 'Miscellaneous Agriculture'},
  {value: 'Miscellaneous Biology'},
  {value: 'Miscellaneous Business & Medical Administration'},
  {value: 'Miscellaneous Education'},
  {value: 'Miscellaneous Engineering'},
  {value: 'Miscellaneous Engineering Technologies'},
  {value: 'Miscellaneous Fine Arts'},
  {value: 'Miscellaneous Health Medical Professions'},
  {value: 'Miscellaneous Psychology'},
  {value: 'Miscellaneous Social Sciences'},
  {value: 'Molecular Biology'},
  {value: 'Multi/Interdisciplinary Studies'},
  {value: 'Multi-Disciplinary Or General Science'},
  {value: 'Music'},
  {value: 'Natural Resources Management'},
  {value: 'Naval Architecture And Marine Engineering'},
  {value: 'Neuroscience'},
  {value: 'Nuclear and Radiological Engineering'},
  {value: 'Nuclear Engineering'},
  {value: 'Nuclear, Industrial Radiology, And Biological Technologies'},
  {value: 'Nursing'},
  {value: 'Nutrition Sciences'},
  {value: 'Oceanography'},
  {value: 'Operations Logistics And E-Commerce'},
  {value: 'Other Foreign Languages'},
  {value: 'Petroleum Engineering'},
  {value: 'Pharmacology'},
  {value: 'Pharmacy Pharmaceutical Sciences And Administration'},
  {value: 'Philosophy And Religious Studies'},
  {value: 'Physical And Health Education Teaching'},
  {value: 'Physical Fitness Parks Recreation And Leisure'},
  {value: 'Physical Sciences'},
  {value: 'Physics'},
  {value: 'Physiology'},
  {value: 'Plant Science And Agronomy'},
  {value: 'Political Science And Government'},
  {value: 'Pre-Law And Legal Studies'},
  {value: 'Psychology'},
  {value: 'Public Administration'},
  {value: 'Public Policy'},
  {value: 'School Student Counseling'},
  {value: 'Science And Computer Teacher Education'},
  {value: 'Secondary Teacher Education'},
  {value: 'Social Psychology'},
  {value: 'Social Science Or History Teacher Education'},
  {value: 'Social Work'},
  {value: 'Sociology'},
  {value: 'Soil Science'},
  {value: 'Special Needs Education'},
  {value: 'Statistics And Decision Science'},
  {value: 'Studio Arts'},
  {value: 'Teacher Education: Multiple Levels'},
  {value: 'Theology And Religious Vocations'},
  {value: 'Transportation Sciences And Technologies'},
  {value: 'Treatment Therapy Professions'},
  {value: 'United States History'},
  {value: 'Visual And Performing Arts'},
  {value: 'Zoology (edited)'},
];


export {schools, locations, majors};
